from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Optional

from ..models.artifacts import Artifacts
from ..models.diagnostics import Diagnostics, ValidationResult
from ..models.plan import SkillPlan


REFERENCE_REQUIRED_SECTIONS = ('## Overview', '## Key points')
REFERENCE_PLACEHOLDER_MARKERS = (
    'Reference placeholder derived from planned candidate resource.',
    'Reference placeholder generated by repair.',
)
SCRIPT_PLACEHOLDER_MARKERS = (
    'placeholder helper script generated from planned candidate resource.',
    'placeholder script generated by repair',
    '# todo',
    '# placeholder',
)
SCRIPT_WRAPPER_MARKERS = (
    '## overview',
    '## key points',
    '## snippet',
    '- source repo:',
    '- source file:',
    'script preview',
    'script wrapper',
    'this helper script',
)
SCRIPT_STRONG_TOKENS = (
    '#!',
    'import ',
    'from ',
    'def ',
    'class ',
    'if __name__ ==',
    'print(',
    'echo ',
    'set -e',
    'function ',
    'const ',
    'let ',
    'var ',
    'export ',
    'package main',
    'fn main',
)
SCRIPT_SUFFIX_HINTS = {
    '.py', '.sh', '.bash', '.zsh', '.js', '.ts', '.tsx', '.jsx', '.rb', '.php', '.pl', '.go', '.rs'
}
PATTERN_CHECK_DESCRIPTION = 'description_mentions_capability_and_trigger'
PATTERN_CHECK_REFERENCE_LINKED = 'reference_files_are_linked_from_skill_md'
PATTERN_CHECK_REFERENCE_NOT_PLACEHOLDER = 'reference_file_is_not_placeholder_heavy'
OPERATION_CONTRACT_PATH = 'references/operations/contract.json'
OPERATION_VALIDATION_PATH = 'evals/operation_validation.json'
OPERATION_COVERAGE_PATH = 'evals/operation_coverage.json'
JSON_DOCUMENTATION_PATTERNS = (
    ' --json',
    '`--json`',
    'json result payload',
    'application/json',
    'structured json',
)


def artifact_paths(artifacts: Artifacts) -> set[str]:
    return {f.path for f in artifacts.files}


def planned_paths(skill_plan: SkillPlan) -> set[str]:
    return set(
        [f.path for f in skill_plan.files_to_create]
        + [f.path for f in skill_plan.files_to_update]
        + [f.path for f in skill_plan.files_to_keep]
    )


def find_file_content(artifacts: Artifacts, path: str) -> Optional[str]:
    for file in artifacts.files:
        if file.path == path:
            return file.content
    return None


def validate_skill_md_frontmatter(content: Optional[str]) -> bool:
    if not content or not content.startswith('---\n'):
        return False

    parts = content.split('---\n', 2)
    if len(parts) < 3:
        return False

    raw = parts[1].strip().splitlines()
    keys = []
    for line in raw:
        if ':' not in line:
            return False
        keys.append(line.split(':', 1)[0].strip())

    return sorted(keys) == ['description', 'name']


def validate_skill_md_budget(content: Optional[str], max_lines: int) -> bool:
    if not content:
        return False
    return len(content.splitlines()) <= max_lines


def _parse_frontmatter(content: Optional[str]) -> dict[str, str]:
    if not content or not content.startswith('---\n'):
        return {}
    parts = content.split('---\n', 2)
    if len(parts) < 3:
        return {}
    frontmatter = {}
    for line in parts[1].strip().splitlines():
        if ':' not in line:
            continue
        key, value = line.split(':', 1)
        frontmatter[key.strip()] = value.strip()
    return frontmatter


def _description_has_capability_and_trigger(description: str) -> bool:
    if not description:
        return False

    lowered = description.lower()
    trigger_markers = ['use when', 'used when', 'when codex needs', 'when the task', 'when you need', '当', '用于']
    trigger_idx = -1
    matched_marker = ''
    for marker in trigger_markers:
        idx = lowered.find(marker)
        if idx != -1:
            trigger_idx = idx
            matched_marker = marker
            break

    if trigger_idx == -1:
        return False

    capability_part = description[:trigger_idx].strip(' ,;:-')
    trigger_part = description[trigger_idx + len(matched_marker):].strip(' ,;:-')
    if not capability_part or len(capability_part) < 8:
        return False
    if not trigger_part or len(trigger_part) < 8:
        return False

    capability_markers = [
        'create', 'refine', 'audit', 'edit', 'analyze', 'generate', 'manage',
        'build', 'review', 'restructure', '查询', '创建', '管理', '审计', '更新', '分析'
    ]
    return any(token in capability_part.lower() for token in capability_markers) or len(capability_part.split()) >= 3


def validate_unreferenced_reference_files(
    artifacts: Artifacts,
    skill_md_content: Optional[str],
) -> list[str]:
    if not skill_md_content:
        return [f.path for f in artifacts.files if f.path.startswith('references/') and f.path != OPERATION_CONTRACT_PATH]

    missing = []
    for file in artifacts.files:
        if file.path == OPERATION_CONTRACT_PATH:
            continue
        if file.path.startswith('references/') and f'`{file.path}`' not in skill_md_content:
            missing.append(file.path)
    return missing


def validate_unsupported_claims(content: Optional[str]) -> bool:
    if not content:
        return False

    suspicious_markers = [
        'production-ready',
        'fully automated',
        'guaranteed',
        'supports everything',
        'complete end-to-end solution',
    ]
    lowered = content.lower()
    return any(marker in lowered for marker in suspicious_markers)


def validate_empty_reference_files(artifacts: Artifacts) -> list[str]:
    empty = []
    for file in artifacts.files:
        if file.path == OPERATION_CONTRACT_PATH:
            continue
        if file.path.startswith('references/') and not (file.content or '').strip():
            empty.append(file.path)
    return empty


def validate_empty_script_files(artifacts: Artifacts) -> list[str]:
    empty = []
    for file in artifacts.files:
        if file.path.startswith('scripts/') and not (file.content or '').strip():
            empty.append(file.path)
    return empty


def validate_empty_eval_files(artifacts: Artifacts) -> list[str]:
    empty = []
    for file in artifacts.files:
        if file.path.startswith('evals/') and file.path.endswith('.json') and not (file.content or '').strip():
            empty.append(file.path)
    return empty


def validate_invalid_eval_scaffold(artifacts: Artifacts) -> list[str]:
    issues = []
    for file in artifacts.files:
        if not (file.path.startswith('evals/') and file.path.endswith('.json')):
            continue

        content = file.content or ''
        if not content.strip():
            continue

        try:
            payload = json.loads(content)
        except Exception:
            issues.append(file.path)
            continue

        if not isinstance(payload, dict) or not payload.get('skill_name'):
            issues.append(file.path)
            continue

        if file.path.endswith('trigger_eval.json') and not isinstance(payload.get('cases'), list):
            issues.append(file.path)
            continue
        if file.path.endswith('output_eval.json') and not isinstance(payload.get('cases'), list):
            issues.append(file.path)
            continue
        if file.path.endswith('benchmark.json') and not isinstance(payload.get('dimensions'), list):
            issues.append(file.path)
            continue

    return issues


def validate_reference_structure_incomplete(artifacts: Artifacts) -> list[str]:
    issues = []
    for file in artifacts.files:
        if file.path == OPERATION_CONTRACT_PATH:
            continue
        if not file.path.startswith('references/'):
            continue
        content = file.content or ''
        if not content.strip():
            continue
        missing_sections = [section for section in REFERENCE_REQUIRED_SECTIONS if section not in content]
        if missing_sections:
            issues.append(file.path)
    return issues


def validate_reference_placeholder_heavy(artifacts: Artifacts) -> list[str]:
    issues = []
    for file in artifacts.files:
        if file.path == OPERATION_CONTRACT_PATH:
            continue
        if not file.path.startswith('references/'):
            continue
        content = file.content or ''
        if not content.strip():
            continue
        if any(marker in content for marker in REFERENCE_PLACEHOLDER_MARKERS):
            issues.append(file.path)
    return issues


def _script_non_empty_lines(content: str) -> list[str]:
    return [line.strip() for line in content.splitlines() if line.strip()]


def _script_code_signal_count(path: str, content: str) -> int:
    score = 0
    stripped = content.strip()
    if not stripped:
        return 0
    if stripped.startswith('#!'):
        score += 2
    lower = stripped.lower()
    for token in SCRIPT_STRONG_TOKENS:
        if token in stripped:
            score += 1
    suffix = Path(path).suffix.lower()
    if suffix == '.py':
        try:
            compile(content, path, 'exec')
            score += 2
        except SyntaxError:
            pass
        except Exception:
            score += 1
    elif suffix in SCRIPT_SUFFIX_HINTS:
        if any(token in stripped for token in ('=', '(', ')', '{', '}', '$', ';')):
            score += 1
    if lower.startswith('python ') or lower.startswith('bash '):
        score -= 1
    return score


def validate_script_placeholder_heavy(artifacts: Artifacts) -> list[str]:
    issues = []
    for file in artifacts.files:
        if not file.path.startswith('scripts/'):
            continue
        content = file.content or ''
        stripped = content.strip()
        if not stripped:
            continue
        lower = stripped.lower()
        non_empty_lines = _script_non_empty_lines(content)
        placeholder_line_count = sum(
            1 for line in non_empty_lines if any(marker in line.lower() for marker in SCRIPT_PLACEHOLDER_MARKERS)
        )
        if placeholder_line_count == 0:
            continue
        if placeholder_line_count >= max(1, len(non_empty_lines) - 1):
            issues.append(file.path)
            continue
        if _script_code_signal_count(file.path, content) <= 1:
            issues.append(file.path)
    return issues


def validate_script_non_code_like(artifacts: Artifacts) -> list[str]:
    issues = []
    for file in artifacts.files:
        if not file.path.startswith('scripts/'):
            continue
        content = file.content or ''
        stripped = content.strip()
        if not stripped:
            continue
        lower = stripped.lower()
        non_empty_lines = _script_non_empty_lines(content)
        code_signals = _script_code_signal_count(file.path, content)
        placeholder_markers = sum(1 for marker in SCRIPT_PLACEHOLDER_MARKERS if marker in lower)
        comment_like_lines = sum(
            1
            for line in non_empty_lines
            if line.startswith('#') or line.startswith('//') or line.startswith('/*') or line.startswith('*')
        )
        markdown_like_lines = sum(
            1
            for line in non_empty_lines[:8]
            if line.startswith('# ')
            or line.startswith('## ')
            or line.startswith('- ')
            or line.startswith('* ')
            or line[:2].isdigit() and line[1:3] == '. '
        )
        wrapper_markers = sum(1 for marker in SCRIPT_WRAPPER_MARKERS if marker in lower)
        if placeholder_markers > 0 and (code_signals <= 1 or comment_like_lines == len(non_empty_lines)):
            issues.append(file.path)
            continue
        if wrapper_markers > 0 and code_signals <= 1:
            issues.append(file.path)
            continue
        if markdown_like_lines >= max(2, len(non_empty_lines[:8]) // 2) and code_signals == 0:
            issues.append(file.path)
    return issues


def validate_script_wrapper_like(artifacts: Artifacts) -> list[str]:
    issues = []
    for path in validate_script_non_code_like(artifacts):
        content = find_file_content(artifacts, path) or ''
        lower = content.lower()
        if any(marker in lower for marker in SCRIPT_WRAPPER_MARKERS) or '```' in content:
            issues.append(path)
    return issues


def _iter_patterns(extracted_patterns: Any) -> list[Any]:
    if extracted_patterns is None:
        return []
    patterns = getattr(extracted_patterns, 'patterns', None)
    if patterns is not None:
        return list(patterns)
    if isinstance(extracted_patterns, dict):
        return list(extracted_patterns.get('patterns', []) or [])
    return []


def _get_attr(obj: Any, key: str, default=None):
    if hasattr(obj, key):
        return getattr(obj, key)
    if isinstance(obj, dict):
        return obj.get(key, default)
    return default


def collect_pattern_validator_checks(extracted_patterns: Any) -> list[str]:
    checks: list[str] = []
    for pattern in _iter_patterns(extracted_patterns):
        status = (_get_attr(pattern, 'status', 'candidate') or 'candidate').lower()
        if status not in {'accepted', 'candidate'}:
            continue
        downstream_hints = _get_attr(pattern, 'downstream_hints', None)
        for check in list(_get_attr(downstream_hints, 'validator_checks', []) or []):
            if check not in checks:
                checks.append(check)
    return checks


def run_pattern_validator_checks(
    *,
    extracted_patterns: Any,
    skill_md_content: Optional[str],
    validation: ValidationResult,
    existing_issue_paths: dict[str, list[str]],
) -> tuple[list[str], list[str]]:
    requested_checks = collect_pattern_validator_checks(extracted_patterns)
    if not requested_checks:
        return [], []

    summary: list[str] = []
    notes: list[str] = []
    frontmatter = _parse_frontmatter(skill_md_content)
    description = frontmatter.get('description', '')

    for check in requested_checks:
        if check == PATTERN_CHECK_DESCRIPTION:
            if not _description_has_capability_and_trigger(description):
                summary.append('Pattern check failed: description should mention both capability and trigger')
            else:
                notes.append('Pattern-aware validator check passed: description_mentions_capability_and_trigger')
        elif check == PATTERN_CHECK_REFERENCE_LINKED:
            if validation.unreferenced_reference_files:
                summary.append('Pattern check failed: reference files should be linked from SKILL.md')
            else:
                notes.append('Pattern-aware validator check passed: reference_files_are_linked_from_skill_md')
        elif check == PATTERN_CHECK_REFERENCE_NOT_PLACEHOLDER:
            if existing_issue_paths.get('reference_placeholder'):
                summary.append('Pattern check failed: reference files should not remain placeholder-heavy')
            else:
                notes.append('Pattern-aware validator check passed: reference_file_is_not_placeholder_heavy')
        else:
            notes.append(f'Pattern-aware validator check skipped (unsupported): {check}')

    if requested_checks:
        notes.append(f'Pattern-aware validator checks requested: {requested_checks}')
    return summary, notes


def classify_validation_issues(validation: ValidationResult) -> tuple[list[str], list[str]]:
    repairable = []
    non_repairable = []

    if not validation.frontmatter_valid:
        repairable.append('invalid_frontmatter')
    if not validation.skill_md_within_budget:
        repairable.append('skill_md_over_budget')
    if not validation.planned_files_present:
        repairable.append('missing_planned_file')
    if validation.unreferenced_reference_files:
        repairable.append('unreferenced_reference')
    if validation.unnecessary_files_present:
        repairable.append('unexpected_file')
    for item in validation.summary:
        if item.startswith('Empty reference file:'):
            repairable.append('empty_reference_file')
        if item.startswith('Empty script file:'):
            repairable.append('empty_script_file')
        if item.startswith('Empty eval scaffold file:'):
            repairable.append('empty_eval_scaffold')
        if item.startswith('Reference structure incomplete:'):
            repairable.append('reference_structure_incomplete')
        if item.startswith('Reference placeholder heavy:'):
            repairable.append('reference_placeholder_heavy')
        if item.startswith('Script placeholder heavy:'):
            repairable.append('script_placeholder_heavy')
        if item.startswith('Script non-code-like:'):
            repairable.append('script_non_code_like')
        if item.startswith('Script wrapper-like:'):
            repairable.append('script_wrapper_like')
        if item.startswith('Invalid eval scaffold:'):
            repairable.append('invalid_eval_scaffold')
        if item.startswith('Pattern check failed: description should mention both capability and trigger'):
            repairable.append('pattern_description_missing_capability_trigger')
        if item.startswith('Pattern check failed: reference files should be linked from SKILL.md'):
            repairable.append('pattern_reference_link_missing')
        if item.startswith('Pattern check failed: reference files should not remain placeholder-heavy'):
            repairable.append('pattern_reference_placeholder_heavy')
        if item.startswith('Operation contract missing:'):
            repairable.append('operation_contract_missing')
        if item.startswith('Operation contract invalid:'):
            repairable.append('operation_contract_invalid')
        if item.startswith('Operation surface incomplete:'):
            repairable.append('operation_surface_incomplete')
        if item.startswith('Operation JSON support mismatch:'):
            repairable.append('operation_json_contract_mismatch')
        if item.startswith('Operation mutating safeguards incomplete:'):
            repairable.append('operation_mutating_missing_safeguards')
        if item.startswith('Operation session model missing from SKILL.md:'):
            repairable.append('operation_session_model_missing')
        if item.startswith('Operation coverage missing:'):
            repairable.append('operation_coverage_missing')
        if item.startswith('Operation coverage invalid:'):
            repairable.append('operation_coverage_invalid')
        if item.startswith('Operation coverage follow-up mismatch:'):
            repairable.append('operation_coverage_followup_mismatch')
    if validation.unsupported_claims_found:
        non_repairable.append('unsupported_claims')

    return sorted(set(repairable)), non_repairable


def _issue_details_notes(*, validation: ValidationResult, issue_paths: dict[str, list[str]]) -> list[str]:
    notes: list[str] = []

    reference_notes = []
    for label in ('empty', 'structure', 'placeholder'):
        paths = issue_paths.get(f'reference_{label}', [])
        if paths:
            reference_notes.append(f'{label}={paths}')
    if reference_notes:
        notes.append('Validator reference diagnostics: ' + '; '.join(reference_notes))

    script_notes = []
    for label in ('empty', 'placeholder', 'non_code_like', 'wrapper_like'):
        paths = issue_paths.get(f'script_{label}', [])
        if paths:
            script_notes.append(f'{label}={paths}')
    if script_notes:
        notes.append('Validator script diagnostics: ' + '; '.join(script_notes))

    eval_notes = []
    for label in ('empty', 'invalid'):
        paths = issue_paths.get(f'eval_{label}', [])
        if paths:
            eval_notes.append(f'{label}={paths}')
    if eval_notes:
        notes.append('Validator eval diagnostics: ' + '; '.join(eval_notes))

    if validation.unreferenced_reference_files:
        notes.append(
            'Validator navigation diagnostics: '
            f'unreferenced_reference_files={validation.unreferenced_reference_files}'
        )

    return notes


def run_rule_validation(
    *,
    request,
    repo_findings,
    skill_plan: SkillPlan,
    artifacts: Artifacts,
    extracted_patterns=None,
) -> Diagnostics:
    skill_md = find_file_content(artifacts, 'SKILL.md')
    expected = planned_paths(skill_plan)
    actual = artifact_paths(artifacts)
    max_lines = getattr(skill_plan.content_budget, 'skill_md_max_lines', 300)

    validation = ValidationResult(
        frontmatter_valid=validate_skill_md_frontmatter(skill_md),
        skill_md_within_budget=validate_skill_md_budget(skill_md, max_lines),
        planned_files_present=expected.issubset(actual),
        unnecessary_files_present=bool(actual - expected),
        unreferenced_reference_files=validate_unreferenced_reference_files(
            artifacts,
            skill_md,
        ),
        unsupported_claims_found=validate_unsupported_claims(skill_md),
    )

    issue_paths = {
        'reference_empty': validate_empty_reference_files(artifacts),
        'script_empty': validate_empty_script_files(artifacts),
        'eval_empty': validate_empty_eval_files(artifacts),
        'reference_structure': validate_reference_structure_incomplete(artifacts),
        'reference_placeholder': validate_reference_placeholder_heavy(artifacts),
        'script_placeholder': validate_script_placeholder_heavy(artifacts),
        'script_non_code_like': validate_script_non_code_like(artifacts),
        'script_wrapper_like': validate_script_wrapper_like(artifacts),
        'eval_invalid': validate_invalid_eval_scaffold(artifacts),
    }

    for path in issue_paths['reference_empty']:
        validation.summary.append(f'Empty reference file: {path}')
    for path in issue_paths['script_empty']:
        validation.summary.append(f'Empty script file: {path}')
    for path in issue_paths['eval_empty']:
        validation.summary.append(f'Empty eval scaffold file: {path}')
    for path in issue_paths['reference_structure']:
        validation.summary.append(f'Reference structure incomplete: {path}')
    for path in issue_paths['reference_placeholder']:
        validation.summary.append(f'Reference placeholder heavy: {path}')
    for path in issue_paths['script_placeholder']:
        validation.summary.append(f'Script placeholder heavy: {path}')
    for path in issue_paths['script_non_code_like']:
        validation.summary.append(f'Script non-code-like: {path}')
    for path in issue_paths['script_wrapper_like']:
        validation.summary.append(f'Script wrapper-like: {path}')
    for path in issue_paths['eval_invalid']:
        validation.summary.append(f'Invalid eval scaffold: {path}')

    if not validation.frontmatter_valid:
        validation.summary.append('SKILL.md frontmatter is invalid')
    if not validation.skill_md_within_budget:
        validation.summary.append('SKILL.md exceeds configured line budget')
    if not validation.planned_files_present:
        validation.summary.append('Some planned files are missing from artifacts')
    if validation.unnecessary_files_present:
        validation.summary.append('Artifacts include unplanned files')
    if validation.unreferenced_reference_files:
        validation.summary.append('Some reference files are not linked from SKILL.md')
    if validation.unsupported_claims_found:
        validation.summary.append('Suspicious unsupported claims found in SKILL.md')

    operation_notes = _validate_operation_contract(
        skill_plan=skill_plan,
        artifacts=artifacts,
        skill_md_content=skill_md,
        validation=validation,
    )

    pattern_summary, pattern_notes = run_pattern_validator_checks(
        extracted_patterns=extracted_patterns,
        skill_md_content=skill_md,
        validation=validation,
        existing_issue_paths=issue_paths,
    )
    validation.summary.extend(pattern_summary)

    repairable, non_repairable = classify_validation_issues(validation)
    validation.repairable_issue_types = repairable
    validation.non_repairable_issue_types = non_repairable
    validation.repair_recommended = bool(repairable)
    validation.failure_reasons = list(validation.summary)

    missing_planned = sorted(expected - actual)
    unexpected_paths = sorted(actual - expected)
    notes = _issue_details_notes(validation=validation, issue_paths=issue_paths)
    notes.extend(pattern_notes)
    if missing_planned:
        notes.append(f'Validator plan coverage diagnostics: missing_planned_files={missing_planned}')
    if unexpected_paths:
        notes.append(f'Validator plan coverage diagnostics: unexpected_files={unexpected_paths}')
    if not validation.frontmatter_valid:
        notes.append('Validator SKILL.md diagnostics: invalid_frontmatter=True')
    if not validation.skill_md_within_budget:
        notes.append(f'Validator SKILL.md diagnostics: skill_md_over_budget=True; max_lines={max_lines}')
    if validation.unsupported_claims_found:
        notes.append('Validator SKILL.md diagnostics: unsupported_claims_found=True')
    if extracted_patterns is not None:
        pattern_set_id = _get_attr(extracted_patterns, 'pattern_set_id', '')
        if pattern_set_id:
            notes.append(f'Validator consumed extracted_patterns={pattern_set_id}')
        validator_defaults = list(_get_attr(_get_attr(extracted_patterns, 'aggregated_hints', None), 'validator_defaults', []) or [])
        if validator_defaults:
            notes.append(f'Validator aggregated defaults: {validator_defaults[:3]}')
    if validation.repair_recommended:
        notes.append(f'Validator repair candidates: {validation.repairable_issue_types}')
    notes.extend(operation_notes)

    return Diagnostics(
        warnings=list(validation.summary),
        errors=[],
        validation=validation,
        notes=notes,
    )


def _validate_operation_contract(
    *,
    skill_plan: SkillPlan,
    artifacts: Artifacts,
    skill_md_content: Optional[str],
    validation: ValidationResult,
) -> list[str]:
    skill_archetype = str(getattr(skill_plan, 'skill_archetype', 'guidance') or 'guidance').strip().lower()
    if skill_archetype != 'operation_backed':
        return []

    notes: list[str] = []
    operation_contract = getattr(skill_plan, 'operation_contract', None)
    if operation_contract is None:
        validation.summary.append('Operation contract missing: skill plan did not carry an operation-backed contract.')
        return notes

    contract_content = find_file_content(artifacts, OPERATION_CONTRACT_PATH)
    if not contract_content:
        validation.summary.append(f'Operation contract missing: expected `{OPERATION_CONTRACT_PATH}` artifact.')
        return notes

    try:
        contract_payload = json.loads(contract_content)
    except Exception:
        validation.summary.append(f'Operation contract invalid: `{OPERATION_CONTRACT_PATH}` is not valid JSON.')
        return notes

    operations = list(getattr(operation_contract, 'operations', []) or [])
    operation_names = [
        getattr(item, 'name', '')
        for group in operations
        for item in list(getattr(group, 'operations', []) or [])
        if getattr(item, 'name', '')
    ]
    if not operations or not operation_names:
        validation.summary.append('Operation surface incomplete: operation-backed skill has no operation groups or operation specs.')

    missing_mentions = [
        name for name in operation_names[:5]
        if skill_md_content is not None and f'`{name}`' not in skill_md_content and name not in skill_md_content
    ]
    if missing_mentions:
        validation.summary.append(
            'Operation surface incomplete: SKILL.md does not mention operation names '
            + ', '.join(missing_mentions[:3])
        )

    supports_json = bool(getattr(operation_contract, 'supports_json', False))
    if supports_json:
        has_json_surface = False
        if skill_md_content and any(marker in skill_md_content.lower() for marker in JSON_DOCUMENTATION_PATTERNS):
            has_json_surface = True
        if not has_json_surface:
            for file in artifacts.files:
                if not file.path.startswith('scripts/'):
                    continue
                lowered = (file.content or '').lower()
                if any(marker in lowered for marker in JSON_DOCUMENTATION_PATTERNS) or 'json.dumps' in lowered or 'json.loads' in lowered:
                    has_json_surface = True
                    break
        if not has_json_surface:
            validation.summary.append('Operation JSON support mismatch: contract expects JSON support but generated skill surface does not document it.')

    mutability = str(getattr(operation_contract, 'mutability', 'read_only') or 'read_only').strip().lower()
    if mutability in {'mixed', 'mutating'}:
        weak_operations = [
            getattr(item, 'name', '')
            for group in operations
            for item in list(getattr(group, 'operations', []) or [])
            if not list(getattr(item, 'side_effects', []) or []) or not list(getattr(item, 'preconditions', []) or [])
        ]
        if weak_operations:
            validation.summary.append(
                'Operation mutating safeguards incomplete: '
                + ', '.join(weak_operations[:3])
                + ' is missing preconditions or side-effect notes.'
            )

    session_model = str(getattr(operation_contract, 'session_model', 'stateless') or 'stateless').strip().lower()
    if session_model == 'session_required':
        if not skill_md_content or 'session' not in skill_md_content.lower():
            validation.summary.append('Operation session model missing from SKILL.md: contract requires a session-aware workflow.')

    if contract_payload.get('backend_kind'):
        notes.append(
            'Validator operation diagnostics: '
            f"backend_kind={contract_payload.get('backend_kind')}; "
            f"supports_json={bool(contract_payload.get('supports_json', False))}; "
            f"session_model={contract_payload.get('session_model', 'stateless')}; "
            f"mutability={contract_payload.get('mutability', 'read_only')}"
        )
    if find_file_content(artifacts, OPERATION_VALIDATION_PATH):
        notes.append(f'Validator operation diagnostics: operation_validation_artifact={OPERATION_VALIDATION_PATH}')
    coverage_content = find_file_content(artifacts, OPERATION_COVERAGE_PATH)
    if not coverage_content:
        validation.summary.append(f'Operation coverage missing: expected `{OPERATION_COVERAGE_PATH}` artifact.')
        return notes
    try:
        coverage_payload = json.loads(coverage_content)
    except Exception:
        validation.summary.append(f'Operation coverage invalid: `{OPERATION_COVERAGE_PATH}` is not valid JSON.')
        return notes
    if not isinstance(coverage_payload, dict):
        validation.summary.append(f'Operation coverage invalid: `{OPERATION_COVERAGE_PATH}` must be a JSON object.')
        return notes
    covered_operations = [
        str(item or '').strip()
        for item in list(coverage_payload.get('covered_operations') or [])
        if str(item or '').strip()
    ]
    missing_operations = [
        str(item or '').strip()
        for item in list(coverage_payload.get('missing_operations') or [])
        if str(item or '').strip()
    ]
    if sorted(set(covered_operations + missing_operations)) != sorted(set(operation_names)):
        validation.summary.append(
            'Operation coverage invalid: operation_coverage.json must account for every contract operation '
            f'({len(operation_names)} declared, {len(set(covered_operations + missing_operations))} tracked).'
        )
    recommended_followup = str(coverage_payload.get('recommended_followup', 'no_change') or 'no_change').strip().lower()
    if not missing_operations and recommended_followup not in {'no_change', 'patch_current'} and operation_names:
        validation.summary.append(
            f'Operation coverage follow-up mismatch: recommended_followup=`{recommended_followup}` is inconsistent with a fully covered operation surface.'
        )
    notes.append(
        'Validator operation diagnostics: '
        f'operation_coverage_artifact={OPERATION_COVERAGE_PATH}; '
        f'recommended_followup={recommended_followup}; '
        f'missing_operations={missing_operations[:3]}'
    )
    return notes
